ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/aluflags.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/aop.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/ar.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/arm.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/arm_alu.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/arm_chip.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/arm_ctrl_comb.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/arm_ctrl_struct.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/arm_dp.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/bop.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/count.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/decode_addresses.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/detect_skip.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/din.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/dout.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/exc.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/forward.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/getreg.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/getregfromlist.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/ir.v
cp    /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/main.v .
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/mapaluops.v
cp    /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/master .
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/mem2.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/models2
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/regfile.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/regfile_struct.v
cp    /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/regsFile.txt .
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/shift.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/shift_carry.v
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/signal.defs
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/signals2.defs
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/test.config
ln -s /home/ecelrc/students/rrajarathnam/vlsi1/lab3/arm/rtl/test.v
